# Generated by Django 5.2.10 on 2026-09-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0021_rutvisita_entregado_por_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutseguimiento',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='ruteo.rutseguimiento'),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='es_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('expirada', 'Expirada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='movil_token',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='opcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='opciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='origen',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automatico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('respuesta', 'Respuesta'), ('llamada', 'Llamada'), ('nota', 'Nota')], default='nota', max_length=20),
        ),
    ]
