# Generated by Django 5.2.10 on 2026-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0022_rutseguimiento_consulta_rutseguimiento_es_conductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutvisita',
            name='tipo',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('recogida', 'Recogida')], db_index=True, default='entrega', max_length=20),
        ),
    ]
