# Generated by Django 5.2.10 on 2026-09-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0024_backfill_tipo_recogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdespacho',
            name='estado_finalizado_conductor',
            field=models.BooleanField(default=False),
        ),
    ]
