# Generated by Django 5.2.10 on 2026-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0025_rutdespacho_estado_finalizado_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='creado_por_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rutnovedad',
            name='origen',
            field=models.CharField(choices=[('app', 'App'), ('legacy', 'App (legacy)'), ('logy', 'LOGY (WhatsApp)')], max_length=20, null=True),
        ),
    ]
