# Generated by Django 5.2.10 on 2026-09-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0026_rutnovedad_creado_por_id_rutnovedad_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutnovedad',
            name='solucionado_por_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='fecha_liberado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rutvisita',
            name='liberado_por_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='RutDespachoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprobado', 'Aprobado'), ('anulado', 'Anulado'), ('asignado', 'Conductor asignado'), ('tomado', 'Tomado por OE'), ('soltado', 'Soltado'), ('finalizado', 'Finalizado por el conductor'), ('reabierto', 'Reabierto por el conductor'), ('terminado', 'Terminado')], db_index=True, max_length=20)),
                ('usuario_id', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ruteo.rutdespacho')),
            ],
            options={
                'db_table': 'rut_despacho_evento',
                'ordering': ['-id'],
            },
        ),
    ]
