# Generated by Django 5.2.10 on 2026-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0027_rutnovedad_solucionado_por_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutseguimiento',
            name='conductor_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rutseguimiento',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rutseguimiento',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('respuesta', 'Respuesta'), ('llamada', 'Llamada'), ('nota', 'Nota'), ('mensaje', 'Mensaje'), ('novedad', 'Novedad')], default='nota', max_length=20),
        ),
    ]
