# Generated by Django 5.2.10 on 2026-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruteo', '0028_rutseguimiento_conductor_id_rutseguimiento_leido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(db_index=True)),
                ('plataforma', models.CharField(choices=[('ios', 'iOS (APNs)'), ('web', 'Web Push')], max_length=10)),
                ('token', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rut_push_token',
                'ordering': ['-id'],
            },
        ),
    ]
