# Generated by Django 5.2.10 on 2026-09-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertical', '0003_verentrega_codigo_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='verentrega',
            name='estado_finalizado_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verentrega',
            name='estado_terminado',
            field=models.BooleanField(default=False),
        ),
    ]
