# Generated by Django 5.2.10 on 2026-09-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0015_agregar_reporte_a_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='checkin_intervalo_horas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
