# Generated by Django 5.2.10 on 2026-10-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedor', '0016_contenedor_checkin_intervalo_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='acceso_seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
